plugins {
    id 'java'
    id 'application'
}

group = 'uk.ac.superfly'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'uk.ac.superfly.SuperflySketch'
}

dependencies {
    implementation 'org.processing:core:4.5.3'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
